//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posled_practos
{
    using System;
    using System.Collections.Generic;
    
    public partial class cheak
    {
        public int id_cheak { get; set; }
        public Nullable<int> tovar_id { get; set; }
        public Nullable<int> cheakkk_id { get; set; }
        public Nullable<int> pol_id { get; set; }
    
        public virtual info_cheak info_cheak { get; set; }
        public virtual polzovatel polzovatel { get; set; }
    }
}
