//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posled_practos
{
    using System;
    using System.Collections.Generic;
    
    public partial class drag_camni
    {
        public int id_camni { get; set; }
        public string name_camni { get; set; }
        public Nullable<int> mesto_dobich_id { get; set; }
        public Nullable<int> ochis_kamen { get; set; }
        public Nullable<int> camen_id { get; set; }
    
        public virtual cena_ukrash cena_ukrash { get; set; }
        public virtual mesto_dobich mesto_dobich { get; set; }
        public virtual ochish_camen ochish_camen { get; set; }
    }
}
