//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posled_practos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class uvEntities : DbContext
    {
        public uvEntities()
            : base("name=uvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cena_ukrash> cena_ukrash { get; set; }
        public virtual DbSet<drag_camni> drag_camni { get; set; }
        public virtual DbSet<info_cheak> info_cheak { get; set; }
        public virtual DbSet<mesto_dobich> mesto_dobich { get; set; }
        public virtual DbSet<ochish_camen> ochish_camen { get; set; }
        public virtual DbSet<polzovatel> polzovatel { get; set; }
        public virtual DbSet<postavchik> postavchik { get; set; }
        public virtual DbSet<rolee> rolee { get; set; }
        public virtual DbSet<strana> strana { get; set; }
        public virtual DbSet<uveliri> uveliri { get; set; }
        public virtual DbSet<cheak> cheak { get; set; }
    }
}
