//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace posled_practos
{
    using System;
    using System.Collections.Generic;
    
    public partial class rolee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public rolee()
        {
            this.polzovatel = new HashSet<polzovatel>();
        }
    
        public int id_role { get; set; }
        public string name_of_reole { get; set; }
        public Nullable<int> uvel_id { get; set; }
        public Nullable<int> posttt_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<polzovatel> polzovatel { get; set; }
        public virtual postavchik postavchik { get; set; }
        public virtual uveliri uveliri { get; set; }
    }
}
